// Les 88 constellations officielles (UAI, 1922-1930).
// star : étoile la plus brillante · season : meilleure saison d'observation en soirée
// hemi : N (boréale), S (australe), Équ (équatoriale) · area : superficie en degrés carrés
// hist : origine et histoire · wiki : titre de l'article Wikipédia francophone

export const CONSTELLATIONS_88 = [
  { id:'and', fr:'Andromède', la:'Andromeda', star:'Alphératz', season:'Automne', hemi:'N', area:722, zodiac:false,
    hist:"Princesse d'Éthiopie enchaînée à un rocher pour expier la vanité de sa mère Cassiopée, offerte au monstre marin Cétus et sauvée par Persée. L'une des 48 constellations de Ptolémée, elle abrite M31, la grande galaxie spirale voisine de la nôtre.",
    wiki:'Andromède (constellation)' },
  { id:'ant', fr:'Machine pneumatique', la:'Antlia', star:'α Antliae', season:'Printemps', hemi:'S', area:239, zodiac:false,
    hist:"Créée en 1752 par l'abbé Nicolas-Louis de Lacaille lors de son séjour au cap de Bonne-Espérance, en hommage à la pompe à air de Denis Papin. Typique des constellations « scientifiques » du siècle des Lumières.",
    wiki:'Machine pneumatique (constellation)' },
  { id:'aps', fr:'Oiseau de paradis', la:'Apus', star:'α Apodis', season:'Été', hemi:'S', area:206, zodiac:false,
    hist:"Introduite en 1603 par Johann Bayer d'après les observations des navigateurs néerlandais Keyser et de Houtman. Son nom grec « apous » signifie « sans pieds » : on croyait alors que les paradisiers, dont les peaux arrivaient mutilées en Europe, n'avaient pas de pattes.",
    wiki:'Oiseau de paradis (constellation)' },
  { id:'aqr', fr:'Verseau', la:'Aquarius', star:'Sadalsuud', season:'Automne', hemi:'Équ', area:980, zodiac:true,
    hist:"L'échanson : Ganymède, jeune prince troyen enlevé par Zeus pour servir le nectar aux dieux de l'Olympe. Constellation du zodiaque connue depuis Babylone, où elle représentait le dieu Ea déversant les eaux — la région du ciel alentour s'appelle « la Mer ».",
    wiki:'Verseau (constellation)' },
  { id:'aql', fr:'Aigle', la:'Aquila', star:'Altaïr', season:'Été', hemi:'Équ', area:652, zodiac:false,
    hist:"L'aigle de Zeus, porteur de sa foudre, qui enleva Ganymède vers l'Olympe. Cataloguée par Ptolémée. Altaïr, son cœur brillant, forme avec Véga et Deneb le grand Triangle d'été.",
    wiki:'Aigle (constellation)' },
  { id:'ara', fr:'Autel', la:'Ara', star:'β Arae', season:'Été', hemi:'S', area:237, zodiac:false,
    hist:"L'autel sur lequel les dieux de l'Olympe scellèrent leur alliance avant la guerre contre les Titans. Pour les Grecs, la Voie Lactée voisine figurait la fumée s'élevant de l'autel. L'une des 48 de Ptolémée.",
    wiki:'Autel (constellation)' },
  { id:'ari', fr:'Bélier', la:'Aries', star:'Hamal', season:'Automne', hemi:'N', area:441, zodiac:true,
    hist:"Le bélier à la Toison d'or qui sauva Phrixos et Hellé, but de la quête de Jason et des Argonautes. Il marquait jadis l'équinoxe de printemps (le « point vernal »), d'où son rang de première constellation du zodiaque.",
    wiki:'Bélier (constellation)' },
  { id:'aur', fr:'Cocher', la:'Auriga', star:'Capella', season:'Hiver', hemi:'N', area:657, zodiac:false,
    hist:"Identifié à Érichthonios, roi mythique d'Athènes et inventeur du char à quatre chevaux. Capella, « la petite chèvre », évoque Amalthée qui allaita Zeus enfant. Région riche en amas ouverts (M36, M37, M38).",
    wiki:'Cocher (constellation)' },
  { id:'boo', fr:'Bouvier', la:'Boötes', star:'Arcturus', season:'Printemps', hemi:'N', area:907, zodiac:false,
    hist:"Le gardien de bœufs qui pousse les Ourses autour du pôle — Arcturus signifie « gardien de l'ourse ». Mentionné dès Homère dans l'Odyssée : c'est l'une des plus anciennes constellations nommées de la littérature.",
    wiki:'Bouvier (constellation)' },
  { id:'cae', fr:'Burin', la:'Caelum', star:'α Caeli', season:'Hiver', hemi:'S', area:125, zodiac:false,
    hist:"Petite constellation créée par Lacaille en 1752 pour honorer le burin du graveur. L'une des zones les plus pauvres du ciel : aucune étoile n'y dépasse la magnitude 4.",
    wiki:'Burin (constellation)' },
  { id:'cam', fr:'Girafe', la:'Camelopardalis', star:'β Camelopardalis', season:'Hiver', hemi:'N', area:757, zodiac:false,
    hist:"Introduite en 1612 par le théologien et cartographe néerlandais Petrus Plancius pour combler le grand vide entre les Ourses et Cassiopée. Son nom latin signifie « chameau-léopard », l'ancien nom de la girafe.",
    wiki:'Girafe (constellation)' },
  { id:'cnc', fr:'Cancer', la:'Cancer', star:'Altarf', season:'Hiver', hemi:'N', area:506, zodiac:true,
    hist:"Le crabe envoyé par Héra pour pincer Héraclès pendant son combat contre l'Hydre de Lerne — écrasé d'un coup de talon, il fut placé au ciel en récompense. La plus discrète des constellations du zodiaque, elle abrite le bel amas de la Crèche (M44).",
    wiki:'Cancer (constellation)' },
  { id:'cvn', fr:'Chiens de chasse', la:'Canes Venatici', star:'Cor Caroli', season:'Printemps', hemi:'N', area:465, zodiac:false,
    hist:"Créée par Johannes Hevelius en 1687 : Astérion et Chara, les deux chiens que le Bouvier tient en laisse. Cor Caroli, « le cœur de Charles », fut nommée en l'honneur du roi Charles Iᵉʳ d'Angleterre. Abrite la galaxie du Tourbillon (M51).",
    wiki:'Chiens de chasse' },
  { id:'cma', fr:'Grand Chien', la:'Canis Major', star:'Sirius', season:'Hiver', hemi:'S', area:380, zodiac:false,
    hist:"Le grand chien d'Orion, ou Lélaps, le chien si rapide qu'aucune proie ne lui échappait. Sirius, l'étoile la plus brillante du ciel, rythmait le calendrier égyptien : son lever annonçait la crue du Nil et les « jours caniculaires ».",
    wiki:'Grand Chien' },
  { id:'cmi', fr:'Petit Chien', la:'Canis Minor', star:'Procyon', season:'Hiver', hemi:'Équ', area:183, zodiac:false,
    hist:"Le second chien d'Orion. Procyon signifie « avant le chien » : elle se lève juste avant Sirius. Parfois identifiée à Maéra, la chienne fidèle d'Icarios, premier vigneron de l'Attique.",
    wiki:'Petit Chien' },
  { id:'cap', fr:'Capricorne', la:'Capricornus', star:'Deneb Algedi', season:'Automne', hemi:'S', area:414, zodiac:true,
    hist:"La chèvre-poisson : le dieu Pan, surpris par le monstre Typhon, plongea dans le Nil — la partie immergée devint queue de poisson. Héritée des Babyloniens (le dieu Ea). Neptune y fut découverte par le calcul en 1846.",
    wiki:'Capricorne (constellation)' },
  { id:'car', fr:'Carène', la:'Carina', star:'Canopus', season:'Hiver', hemi:'S', area:494, zodiac:false,
    hist:"La coque du Navire Argo, l'immense constellation antique du vaisseau de Jason que Lacaille découpa en trois (Carène, Poupe, Voiles) au XVIIIᵉ siècle. Canopus, 2ᵉ étoile du ciel, servait de repère aux navigateurs ; la nébuleuse de la Carène abrite Eta Carinae, candidate à la supernova.",
    wiki:'Carène (constellation)' },
  { id:'cas', fr:'Cassiopée', la:'Cassiopeia', star:'Schedar', season:'Automne', hemi:'N', area:598, zodiac:false,
    hist:"La reine d'Éthiopie qui osa se prétendre plus belle que les Néréides, déclenchant la colère de Poséidon. Condamnée à tourner autour du pôle, tête en bas la moitié du temps. Son « W » est l'un des repères les plus sûrs du ciel boréal.",
    wiki:'Cassiopée (constellation)' },
  { id:'cen', fr:'Centaure', la:'Centaurus', star:'Alpha Centauri', season:'Printemps', hemi:'S', area:1060, zodiac:false,
    hist:"Chiron, le centaure sage, précepteur d'Achille et d'Asclépios, blessé par une flèche empoisonnée d'Héraclès. Alpha Centauri est le système stellaire le plus proche du Soleil (4,37 al) ; Oméga du Centaure est le plus grand amas globulaire de la Galaxie.",
    wiki:'Centaure (constellation)' },
  { id:'cep', fr:'Céphée', la:'Cepheus', star:'Aldéramin', season:'Automne', hemi:'N', area:588, zodiac:false,
    hist:"Le roi d'Éthiopie, époux de Cassiopée et père d'Andromède. Constellation circumpolaire en forme de maison. Delta Cephei y donna son nom aux céphéides, ces étoiles variables qui servent à mesurer les distances dans l'Univers.",
    wiki:'Céphée (constellation)' },
  { id:'cet', fr:'Baleine', la:'Cetus', star:'Diphda', season:'Automne', hemi:'Équ', area:1231, zodiac:false,
    hist:"Cétus, le monstre marin envoyé dévorer Andromède, pétrifié par Persée brandissant la tête de Méduse. Quatrième constellation du ciel par la taille, elle abrite Mira, « la Merveilleuse », première étoile variable reconnue (1596).",
    wiki:'Baleine (constellation)' },
  { id:'cha', fr:'Caméléon', la:'Chamaeleon', star:'α Chamaeleontis', season:'Printemps', hemi:'S', area:132, zodiac:false,
    hist:"Petite constellation australe de Bayer (1603), d'après les navigateurs néerlandais fascinés par la faune exotique des tropiques. Proche du pôle sud céleste, invisible depuis l'Europe.",
    wiki:'Caméléon (constellation)' },
  { id:'cir', fr:'Compas', la:'Circinus', star:'α Circini', season:'Été', hemi:'S', area:93, zodiac:false,
    hist:"Le compas du dessinateur, créé par Lacaille en 1752 près du Triangle austral. Quatrième plus petite constellation du ciel.",
    wiki:'Compas (constellation)' },
  { id:'col', fr:'Colombe', la:'Columba', star:'Phact', season:'Hiver', hemi:'S', area:270, zodiac:false,
    hist:"Créée par Plancius en 1592 : la colombe de Noé portant le rameau d'olivier, envoyée chercher la terre ferme après le Déluge — ou celle que les Argonautes lâchèrent entre les roches Symplégades.",
    wiki:'Colombe (constellation)' },
  { id:'com', fr:'Chevelure de Bérénice', la:'Coma Berenices', star:'β Comae Berenices', season:'Printemps', hemi:'N', area:386, zodiac:false,
    hist:"La reine Bérénice II d'Égypte sacrifia sa chevelure à Aphrodite pour le retour victorieux de son époux ; l'astronome Conon de Samos déclara que les dieux l'avaient placée au ciel. Seule constellation nommée d'après un personnage historique réel. Fenêtre sur l'amas de galaxies de la Vierge.",
    wiki:'Chevelure de Bérénice' },
  { id:'cra', fr:'Couronne australe', la:'Corona Australis', star:'Meridiana', season:'Été', hemi:'S', area:128, zodiac:false,
    hist:"Petit diadème d'étoiles aux pieds du Sagittaire, déjà cataloguée par Ptolémée. Parfois vue comme la couronne de laurier que le centaure aurait déposée, ou celle de Dionysos plaçant sa mère Sémélé parmi les dieux.",
    wiki:'Couronne australe' },
  { id:'crb', fr:'Couronne boréale', la:'Corona Borealis', star:'Alphecca', season:'Été', hemi:'N', area:179, zodiac:false,
    hist:"Le diadème d'Ariane, offert par Dionysos qui l'épousa après son abandon par Thésée sur l'île de Naxos — lancé au ciel, ses joyaux devinrent étoiles. Son arc de cercle presque parfait est immanquable entre le Bouvier et Hercule.",
    wiki:'Couronne boréale' },
  { id:'crv', fr:'Corbeau', la:'Corvus', star:'Gienah', season:'Printemps', hemi:'S', area:184, zodiac:false,
    hist:"L'oiseau d'Apollon, envoyé chercher de l'eau avec une coupe : s'étant attardé à manger des figues, il revint avec un serpent d'eau en guise d'excuse. Apollon, furieux, plaça au ciel le corbeau, la Coupe et l'Hydre — le serpent empêchant à jamais l'oiseau de boire.",
    wiki:'Corbeau (constellation)' },
  { id:'crt', fr:'Coupe', la:'Crater', star:'δ Crateris', season:'Printemps', hemi:'S', area:282, zodiac:false,
    hist:"La coupe d'Apollon, liée au mythe du Corbeau et de l'Hydre. Constellation discrète de Ptolémée, posée sur le dos du grand serpent d'eau.",
    wiki:'Coupe (constellation)' },
  { id:'cru', fr:'Croix du Sud', la:'Crux', star:'Acrux', season:'Printemps', hemi:'S', area:68, zodiac:false,
    hist:"La plus petite constellation du ciel, mais la plus célèbre de l'hémisphère austral. Connue des Anciens (alors visible de Méditerranée), elle fut détachée du Centaure au XVIᵉ siècle par les navigateurs européens, pour qui elle indiquait le sud. Figure sur cinq drapeaux nationaux.",
    wiki:'Croix du Sud' },
  { id:'cyg', fr:'Cygne', la:'Cygnus', star:'Deneb', season:'Été', hemi:'N', area:804, zodiac:false,
    hist:"Zeus métamorphosé en cygne pour séduire Léda, reine de Sparte — de leur union naquirent Hélène et les Dioscures. Sa grande croix, la « Croix du Nord », vole le long de la Voie Lactée ; Albireo, sa tête, est l'une des plus belles étoiles doubles du ciel.",
    wiki:'Cygne (constellation)' },
  { id:'del', fr:'Dauphin', la:'Delphinus', star:'Rotanev', season:'Été', hemi:'N', area:189, zodiac:false,
    hist:"Le dauphin qui convainquit la néréide Amphitrite d'épouser Poséidon, ou celui qui sauva le poète Arion jeté à la mer par des pirates. Ses étoiles Sualocin et Rotanev cachent une facétie : lues à l'envers, elles donnent « Nicolaus Venator », l'assistant de l'observatoire de Palerme qui les nomma.",
    wiki:'Dauphin (constellation)' },
  { id:'dor', fr:'Dorade', la:'Dorado', star:'α Doradus', season:'Hiver', hemi:'S', area:179, zodiac:false,
    hist:"Le poisson-coryphène des mers tropicales, introduit par Bayer en 1603. Elle abrite l'essentiel du Grand Nuage de Magellan, galaxie satellite de la Voie Lactée, et la nébuleuse de la Tarentule, la plus vaste pouponnière d'étoiles du Groupe local.",
    wiki:'Dorade (constellation)' },
  { id:'dra', fr:'Dragon', la:'Draco', star:'Eltanin', season:'Été', hemi:'N', area:1083, zodiac:false,
    hist:"Ladon, le dragon qui gardait les pommes d'or du jardin des Hespérides, vaincu par Héraclès. S'enroule entre les deux Ourses. Thuban, dans sa queue, était l'étoile polaire à l'époque des pyramides d'Égypte, il y a 4 700 ans.",
    wiki:'Dragon (constellation)' },
  { id:'equ', fr:'Petit Cheval', la:'Equuleus', star:'Kitalpha', season:'Automne', hemi:'N', area:72, zodiac:false,
    hist:"Deuxième plus petite constellation du ciel, déjà présente chez Ptolémée. Parfois identifiée à Céléris, frère ou fils de Pégase, offert à Castor par Hermès.",
    wiki:'Petit Cheval' },
  { id:'eri', fr:'Éridan', la:'Eridanus', star:'Achernar', season:'Hiver', hemi:'S', area:1138, zodiac:false,
    hist:"Le fleuve mythique dans lequel s'abîma Phaéton, foudroyé par Zeus après avoir perdu le contrôle du char du Soleil. Longue rivière d'étoiles serpentant d'Orion jusqu'au ciel austral profond, où brille Achernar, « la fin du fleuve ».",
    wiki:'Éridan (constellation)' },
  { id:'for', fr:'Fourneau', la:'Fornax', star:'α Fornacis', season:'Automne', hemi:'S', area:398, zodiac:false,
    hist:"Le fourneau du chimiste, créé par Lacaille en hommage à Antoine Lavoisier… des décennies avant la célébrité de celui-ci — il honorait en fait le fourneau à distiller. Sa zone pauvre en étoiles offre une fenêtre profonde : l'amas de galaxies du Fourneau y a été longuement observé par Hubble et le JWST.",
    wiki:'Fourneau (constellation)' },
  { id:'gem', fr:'Gémeaux', la:'Gemini', star:'Pollux', season:'Hiver', hemi:'N', area:514, zodiac:true,
    hist:"Castor et Pollux, les Dioscures, jumeaux de Léda : l'un mortel, l'autre immortel. Pollux partagea son immortalité pour ne pas être séparé de son frère. Protecteurs des marins, ils brillent côte à côte au-dessus d'Orion. Pluton y fut découverte en 1930.",
    wiki:'Gémeaux (constellation)' },
  { id:'gru', fr:'Grue', la:'Grus', star:'Alnair', season:'Automne', hemi:'S', area:366, zodiac:false,
    hist:"L'oiseau échassier des navigateurs néerlandais, introduit par Bayer en 1603. La grue était dans l'Égypte ancienne le symbole de l'astronome — un choix élégant pour une constellation.",
    wiki:'Grue (constellation)' },
  { id:'her', fr:'Hercule', la:'Hercules', star:'Kornephoros', season:'Été', hemi:'N', area:1225, zodiac:false,
    hist:"Le héros aux douze travaux, représenté agenouillé, massue levée, un pied sur la tête du Dragon. Cinquième constellation du ciel par la taille. Son « trapèze » central guide vers M13, le grand amas globulaire d'Hercule et ses 300 000 étoiles.",
    wiki:'Hercule (constellation)' },
  { id:'hor', fr:'Horloge', la:'Horologium', star:'α Horologii', season:'Hiver', hemi:'S', area:249, zodiac:false,
    hist:"L'horloge à pendule de Lacaille (1752), hommage à l'invention de Christiaan Huygens qui révolutionna l'astronomie de précision. Constellation australe discrète et étirée.",
    wiki:'Horloge (constellation)' },
  { id:'hya', fr:'Hydre', la:'Hydra', star:'Alphard', season:'Printemps', hemi:'S', area:1303, zodiac:false,
    hist:"La plus grande constellation du ciel : le serpent d'eau s'étire sur plus de 100°, un quart du tour d'horizon. Liée à l'hydre de Lerne vaincue par Héraclès et au mythe du Corbeau. Alphard, « la solitaire », est sa seule étoile brillante.",
    wiki:'Hydre (constellation)' },
  { id:'hyi', fr:'Hydre mâle', la:'Hydrus', star:'β Hydri', season:'Hiver', hemi:'S', area:243, zodiac:false,
    hist:"Le petit serpent d'eau austral de Bayer (1603), pendant de la grande Hydre de Ptolémée. Glisse entre les deux Nuages de Magellan, près du pôle sud céleste.",
    wiki:'Hydre mâle' },
  { id:'ind', fr:'Indien', la:'Indus', star:'α Indi', season:'Automne', hemi:'S', area:294, zodiac:false,
    hist:"Figure d'un Indien créée par Bayer (1603) d'après les peuples rencontrés par les grands navigateurs — sans qu'on sache s'il s'agissait des Indes orientales, de Madagascar ou des Amériques. Epsilon Indi, à 11,9 al, est l'une des étoiles proches les plus étudiées.",
    wiki:'Indien (constellation)' },
  { id:'lac', fr:'Lézard', la:'Lacerta', star:'α Lacertae', season:'Automne', hemi:'N', area:201, zodiac:false,
    hist:"Créée par Hevelius en 1687 dans un étroit couloir entre le Cygne et Andromède — « aucun animal plus grand n'y tenait », expliqua-t-il. Son zigzag d'étoiles faibles évoque un petit W. BL Lacertae y a donné son nom à toute une classe de noyaux actifs de galaxies.",
    wiki:'Lézard (constellation)' },
  { id:'leo', fr:'Lion', la:'Leo', star:'Régulus', season:'Printemps', hemi:'N', area:947, zodiac:true,
    hist:"Le lion de Némée, à la peau impénétrable, étouffé par Héraclès lors de son premier travail. Une des rares constellations qui ressemble à sa figure : sa « faucille » dessine la crinière. Régulus, « le petit roi », fut l'une des quatre étoiles royales de Perse. Les Léonides en rayonnent chaque novembre.",
    wiki:'Lion (constellation)' },
  { id:'lmi', fr:'Petit Lion', la:'Leo Minor', star:'Praecipua', season:'Printemps', hemi:'N', area:232, zodiac:false,
    hist:"Glissé par Hevelius en 1687 entre le Lion et la Grande Ourse. Curiosité : suite à une erreur historique de catalogage, c'est la seule constellation sans étoile « alpha » — sa plus brillante est 46 LMi, dite Praecipua.",
    wiki:'Petit Lion' },
  { id:'lep', fr:'Lièvre', la:'Lepus', star:'Arneb', season:'Hiver', hemi:'S', area:290, zodiac:false,
    hist:"Le gibier favori d'Orion, placé aux pieds du chasseur, éternellement poursuivi par le Grand Chien. Constellation de Ptolémée. Abrite la « Crimson Star » (R Leporis), l'une des étoiles les plus rouges du ciel.",
    wiki:'Lièvre (constellation)' },
  { id:'lib', fr:'Balance', la:'Libra', star:'Zubeneschamali', season:'Été', hemi:'S', area:538, zodiac:true,
    hist:"Seul objet inanimé du zodiaque. Pour les Grecs, ses étoiles étaient les pinces du Scorpion — leurs noms arabes le rappellent encore (Zubenelgenubi, « la pince du sud »). Les Romains en firent la balance de la justice, tenue par la Vierge voisine (Astrée).",
    wiki:'Balance (constellation)' },
  { id:'lup', fr:'Loup', la:'Lupus', star:'α Lupi', season:'Été', hemi:'S', area:334, zodiac:false,
    hist:"Pour les Grecs, une « bête sauvage » indéterminée, embrochée par le Centaure voisin sur sa lance — la Renaissance en fit un loup. En 1006, la supernova la plus brillante de l'histoire y est apparue, visible en plein jour pendant des semaines.",
    wiki:'Loup (constellation)' },
  { id:'lyn', fr:'Lynx', la:'Lynx', star:'α Lyncis', season:'Hiver', hemi:'N', area:545, zodiac:false,
    hist:"Hevelius (1687) la nomma ainsi avec humour : ses étoiles sont si faibles « qu'il faut des yeux de lynx pour la voir ». Comble le vide entre la Grande Ourse et le Cocher.",
    wiki:'Lynx (constellation)' },
  { id:'lyr', fr:'Lyre', la:'Lyra', star:'Véga', season:'Été', hemi:'N', area:286, zodiac:false,
    hist:"La lyre d'Orphée, dont la musique charmait bêtes et rochers et faillit ramener Eurydice des Enfers. Véga, joyau bleu du Triangle d'été, fut la première étoile photographiée (1850) et sera notre étoile polaire dans 12 000 ans. Abrite la nébuleuse de l'Anneau (M57).",
    wiki:'Lyre (constellation)' },
  { id:'men', fr:'Table', la:'Mensa', star:'α Mensae', season:'Hiver', hemi:'S', area:153, zodiac:false,
    hist:"Seule constellation nommée d'après un lieu terrestre : la montagne de la Table au Cap, sous laquelle Lacaille dressa son observatoire. Le Grand Nuage de Magellan qui la borde évoque la « nappe » de nuages coiffant la vraie montagne. Sa plus brillante étoile plafonne à magnitude 5,1 — record de discrétion.",
    wiki:'Table (constellation)' },
  { id:'mic', fr:'Microscope', la:'Microscopium', star:'γ Microscopii', season:'Automne', hemi:'S', area:210, zodiac:false,
    hist:"Le microscope de Lacaille (1752), hommage aux instruments qui ouvraient alors l'infiniment petit pendant que les télescopes ouvraient l'infiniment grand.",
    wiki:'Microscope (constellation)' },
  { id:'mon', fr:'Licorne', la:'Monoceros', star:'β Monocerotis', season:'Hiver', hemi:'Équ', area:482, zodiac:false,
    hist:"Créée par Plancius en 1612, peut-être inspirée des licornes de la Bible. Discrète mais traversée par la Voie Lactée, elle regorge de trésors : la nébuleuse de la Rosette, l'amas de l'Arbre de Noël et la spectaculaire étoile triple β Mon.",
    wiki:'Licorne (constellation)' },
  { id:'mus', fr:'Mouche', la:'Musca', star:'α Muscae', season:'Printemps', hemi:'S', area:138, zodiac:false,
    hist:"Petite constellation australe de Bayer (1603), d'abord nommée « l'Abeille » avant de devenir la Mouche. Seul insecte du ciel, posée juste sous la Croix du Sud.",
    wiki:'Mouche (constellation)' },
  { id:'nor', fr:'Règle', la:'Norma', star:'γ² Normae', season:'Été', hemi:'S', area:165, zodiac:false,
    hist:"L'équerre du dessinateur, créée par Lacaille (1752) dans une zone riche de la Voie Lactée australe. Le « Grand Attracteur », mystérieuse concentration de masse qui attire notre Galaxie, se cache derrière ses champs d'étoiles.",
    wiki:'Règle (constellation)' },
  { id:'oct', fr:'Octant', la:'Octans', star:'ν Octantis', season:'Printemps', hemi:'S', area:291, zodiac:false,
    hist:"L'octant de navigation, par Lacaille. Contient le pôle sud céleste : Sigma Octantis, magnitude 5,4, est l'équivalent austral — bien pâle — de notre étoile Polaire. Les navigateurs lui préfèrent la Croix du Sud.",
    wiki:'Octant (constellation)' },
  { id:'oph', fr:'Ophiuchus', la:'Ophiuchus', star:'Rasalhague', season:'Été', hemi:'Équ', area:948, zodiac:false,
    hist:"Le Serpentaire : Asclépios, dieu de la médecine, si habile qu'il ressuscitait les morts — Zeus le foudroya pour préserver l'ordre du monde. Le Soleil le traverse chaque année du 30 novembre au 18 décembre : c'est la « 13ᵉ constellation du zodiaque ». Képler y observa sa supernova en 1604.",
    wiki:'Ophiuchus' },
  { id:'ori', fr:'Orion', la:'Orion', star:'Rigel', season:'Hiver', hemi:'Équ', area:594, zodiac:false,
    hist:"Le chasseur géant, tué par le Scorpion envoyé par Gaïa — les deux constellations sont placées aux antipodes pour ne jamais se croiser. La plus spectaculaire du ciel : Rigel et Bételgeuse l'encadrent, son Baudrier de trois étoiles guide vers Sirius et Aldébaran, et son épée porte la grande nébuleuse M42.",
    wiki:'Orion (constellation)' },
  { id:'pav', fr:'Paon', la:'Pavo', star:'Peacock', season:'Été', hemi:'S', area:378, zodiac:false,
    hist:"L'oiseau sacré d'Héra, dont la déesse orna la queue des cent yeux d'Argos. Constellation australe de Bayer (1603). Son étoile Peacock fut nommée dans les années 1930 pour les besoins de la navigation aérienne britannique.",
    wiki:'Paon (constellation)' },
  { id:'peg', fr:'Pégase', la:'Pegasus', star:'Enif', season:'Automne', hemi:'N', area:1121, zodiac:false,
    hist:"Le cheval ailé né du sang de Méduse décapitée par Persée, monture de Bellérophon contre la Chimère. Son « Grand Carré » domine le ciel d'automne. 51 Pegasi b, première exoplanète détectée autour d'une étoile de type solaire (1995, Nobel 2019), orbite dans cette constellation.",
    wiki:'Pégase (constellation)' },
  { id:'per', fr:'Persée', la:'Perseus', star:'Mirphak', season:'Automne', hemi:'N', area:615, zodiac:false,
    hist:"Le héros qui décapita Méduse et sauva Andromède. Algol, « la tête du démon » qu'il brandit, baisse d'éclat toutes les 69 heures — une binaire à éclipses qui troublait déjà les Anciens. Les Perséides en rayonnent chaque mois d'août, et son Double Amas est un joyau des jumelles.",
    wiki:'Persée (constellation)' },
  { id:'phe', fr:'Phénix', la:'Phoenix', star:'Ankaa', season:'Automne', hemi:'S', area:469, zodiac:false,
    hist:"L'oiseau mythique qui renaît de ses cendres, choisi par Bayer (1603). La plus grande des douze constellations créées d'après les navigateurs néerlandais.",
    wiki:'Phénix (constellation)' },
  { id:'pic', fr:'Peintre', la:'Pictor', star:'α Pictoris', season:'Hiver', hemi:'S', area:247, zodiac:false,
    hist:"Le chevalet du peintre, par Lacaille. Bêta Pictoris y est entourée du premier disque de poussières jamais photographié autour d'une étoile (1984) — un système planétaire en formation, devenu une icône de l'astronomie moderne.",
    wiki:'Peintre (constellation)' },
  { id:'psc', fr:'Poissons', la:'Pisces', star:'Alpherg', season:'Automne', hemi:'Équ', area:889, zodiac:true,
    hist:"Aphrodite et son fils Éros, changés en poissons pour fuir le monstre Typhon, liés par un ruban pour ne pas se perdre. Constellation du zodiaque qui contient aujourd'hui le point vernal — la position du Soleil à l'équinoxe de printemps.",
    wiki:'Poissons (constellation)' },
  { id:'psa', fr:'Poisson austral', la:'Piscis Austrinus', star:'Fomalhaut', season:'Automne', hemi:'S', area:245, zodiac:false,
    hist:"Le « grand poisson » des Babyloniens, parent des Poissons du zodiaque, qui boit l'eau versée par le Verseau. Fomalhaut, « la bouche du poisson », est l'étoile brillante la plus solitaire du ciel d'automne, entourée d'un vaste anneau de débris.",
    wiki:'Poisson austral' },
  { id:'pup', fr:'Poupe', la:'Puppis', star:'Naos', season:'Hiver', hemi:'S', area:673, zodiac:false,
    hist:"Le château arrière du Navire Argo, démantelé par Lacaille. La plus vaste des trois pièces du navire, traversée par la Voie Lactée et riche en amas ouverts (M46, M47). Naos est l'une des étoiles les plus chaudes visibles à l'œil nu (42 000 K).",
    wiki:'Poupe (constellation)' },
  { id:'pyx', fr:'Boussole', la:'Pyxis', star:'α Pyxidis', season:'Printemps', hemi:'S', area:221, zodiac:false,
    hist:"Le compas de marine, ajouté par Lacaille près de l'ancien Navire Argo — clin d'œil moderne au vaisseau mythique qui naviguait sans instrument.",
    wiki:'Boussole (constellation)' },
  { id:'ret', fr:'Réticule', la:'Reticulum', star:'α Reticuli', season:'Hiver', hemi:'S', area:114, zodiac:false,
    hist:"Le réticule de visée que Lacaille avait placé dans l'oculaire de sa lunette pour cataloguer 10 000 étoiles australes en deux ans — il immortalisa ainsi son propre instrument de mesure.",
    wiki:'Réticule (constellation)' },
  { id:'sge', fr:'Flèche', la:'Sagitta', star:'γ Sagittae', season:'Été', hemi:'N', area:80, zodiac:false,
    hist:"Troisième plus petite constellation, déjà chez Ptolémée. Flèche d'Héraclès tuant l'aigle qui dévorait le foie de Prométhée, ou trait d'Éros — elle vole, bien visible, en pleine Voie Lactée entre l'Aigle et le Cygne.",
    wiki:'Flèche (constellation)' },
  { id:'sgr', fr:'Sagittaire', la:'Sagittarius', star:'Kaus Australis', season:'Été', hemi:'S', area:867, zodiac:true,
    hist:"Le centaure archer, souvent identifié à Crotos, inventeur du tir à l'arc, visant le Scorpion voisin. Sa « théière » d'étoiles pointe vers le centre de la Voie Lactée et le trou noir supermassif Sagittarius A* (4 millions de masses solaires, imagé en 2022). La région la plus riche du ciel en nébuleuses : Lagune, Trifide, Oméga…",
    wiki:'Sagittaire (constellation)' },
  { id:'sco', fr:'Scorpion', la:'Scorpius', star:'Antarès', season:'Été', hemi:'S', area:497, zodiac:true,
    hist:"Le scorpion envoyé par Gaïa pour tuer Orion le chasseur trop vantard — placés aux antipodes, l'un se couche quand l'autre se lève. Une des rares constellations fidèles à sa figure, avec son dard recourbé. Antarès, « la rivale de Mars », est une supergéante rouge 700 fois plus large que le Soleil.",
    wiki:'Scorpion (constellation)' },
  { id:'scl', fr:'Sculpteur', la:'Sculptor', star:'α Sculptoris', season:'Automne', hemi:'S', area:475, zodiac:false,
    hist:"« L'atelier du sculpteur » de Lacaille. Contient le pôle sud galactique : on y regarde perpendiculairement au disque de la Voie Lactée, fenêtre idéale sur les galaxies lointaines comme la belle NGC 253, la galaxie du Sculpteur.",
    wiki:'Sculpteur (constellation)' },
  { id:'sct', fr:'Écu de Sobieski', la:'Scutum', star:'α Scuti', season:'Été', hemi:'S', area:109, zodiac:false,
    hist:"Créée par Hevelius en 1684 pour honorer le roi de Pologne Jean III Sobieski, vainqueur du siège de Vienne — la seule constellation « politique » qui ait survécu. Minuscule mais posée sur un nuage stellaire brillant de la Voie Lactée, avec le superbe amas du Canard sauvage (M11).",
    wiki:'Écu de Sobieski' },
  { id:'ser', fr:'Serpent', la:'Serpens', star:'Unukalhai', season:'Été', hemi:'Équ', area:637, zodiac:false,
    hist:"Le serpent d'Asclépios, symbole de la médecine — sa mue représentait la guérison. Unique constellation en deux morceaux : la Tête (Caput) et la Queue (Cauda), séparées par Ophiuchus qui le tient à bras-le-corps. La Queue abrite la nébuleuse de l'Aigle et ses Piliers de la Création.",
    wiki:'Serpent (constellation)' },
  { id:'sex', fr:'Sextant', la:'Sextans', star:'α Sextantis', season:'Printemps', hemi:'Équ', area:314, zodiac:false,
    hist:"Hevelius (1687) y immortalisa son grand sextant astronomique, détruit dans l'incendie de son observatoire de Dantzig en 1679. Il mesurait les positions d'étoiles à l'œil nu, refusant les lunettes — avec une précision restée légendaire.",
    wiki:'Sextant (constellation)' },
  { id:'tau', fr:'Taureau', la:'Taurus', star:'Aldébaran', season:'Hiver', hemi:'N', area:797, zodiac:true,
    hist:"Zeus métamorphosé en taureau blanc pour enlever la princesse Europe. L'une des plus anciennes figures du ciel — peut-être déjà peinte à Lascaux. Aldébaran, son œil rouge, précède les Pléiades et les Hyades ; la nébuleuse du Crabe (M1) est le vestige de la supernova de 1054 notée par les astronomes chinois.",
    wiki:'Taureau (constellation)' },
  { id:'tel', fr:'Télescope', la:'Telescopium', star:'α Telescopii', season:'Été', hemi:'S', area:252, zodiac:false,
    hist:"Hommage de Lacaille aux grandes lunettes aériennes de l'Observatoire de Paris. Constellation discrète au sud du Sagittaire.",
    wiki:'Télescope (constellation)' },
  { id:'tri', fr:'Triangle', la:'Triangulum', star:'β Trianguli', season:'Automne', hemi:'N', area:132, zodiac:false,
    hist:"Simple triangle d'étoiles déjà catalogué par Ptolémée — les Grecs y voyaient le delta du Nil ou la Sicile. Abrite M33, la galaxie du Triangle, troisième grande spirale du Groupe local et objet le plus lointain visible à l'œil nu sous un ciel parfait.",
    wiki:'Triangle (constellation)' },
  { id:'tra', fr:'Triangle austral', la:'Triangulum Australe', star:'Atria', season:'Été', hemi:'S', area:110, zodiac:false,
    hist:"Le pendant austral du Triangle, plus brillant que son homologue boréal, introduit par Bayer (1603). Ses trois étoiles principales furent surnommées « les Trois Patriarches » par les navigateurs.",
    wiki:'Triangle austral' },
  { id:'tuc', fr:'Toucan', la:'Tucana', star:'α Tucanae', season:'Automne', hemi:'S', area:295, zodiac:false,
    hist:"L'oiseau au grand bec des tropiques, par Bayer (1603). Constellation modeste mais au contenu exceptionnel : le Petit Nuage de Magellan et 47 Tucanae, deuxième plus bel amas globulaire du ciel.",
    wiki:'Toucan (constellation)' },
  { id:'uma', fr:'Grande Ourse', la:'Ursa Major', star:'Alioth', season:'Printemps', hemi:'N', area:1280, zodiac:false,
    hist:"Callisto, nymphe aimée de Zeus, changée en ourse par Héra jalouse et placée au ciel avec son fils Arcas (la Petite Ourse). Troisième constellation par la taille, connue de presque toutes les cultures. Son Grand Chariot de sept étoiles guide vers la Polaire ; Mizar et Alcor forment le célèbre « test de vue » des Anciens.",
    wiki:'Grande Ourse' },
  { id:'umi', fr:'Petite Ourse', la:'Ursa Minor', star:'Polaire', season:'Été', hemi:'N', area:256, zodiac:false,
    hist:"Arcas, fils de Callisto, ou l'une des nymphes qui élevèrent Zeus en Crète. Attribuée au philosophe Thalès, qui l'aurait empruntée aux navigateurs phéniciens. Au bout de sa queue brille l'étoile Polaire, pivot du ciel boréal à moins d'un degré du pôle céleste.",
    wiki:'Petite Ourse' },
  { id:'vel', fr:'Voiles', la:'Vela', star:'γ Velorum', season:'Printemps', hemi:'S', area:500, zodiac:false,
    hist:"Les voiles du Navire Argo. Gamma Velorum, « le joyau spectral », est l'étoile de Wolf-Rayet la plus brillante du ciel. Le pulsar des Voiles, vestige d'une supernova vieille de 11 000 ans, est l'une des sources gamma les plus intenses connues.",
    wiki:'Voiles (constellation)' },
  { id:'vir', fr:'Vierge', la:'Virgo', star:'Spica', season:'Printemps', hemi:'Équ', area:1294, zodiac:true,
    hist:"Déméter, déesse des moissons, ou Astrée, déesse de la justice, dernière immortelle à quitter la Terre à la fin de l'âge d'or. Spica, « l'épi de blé », confirme le lien aux récoltes. Deuxième constellation du ciel, elle ouvre sur l'amas de la Vierge et ses 2 000 galaxies — dont M87 et son trou noir photographié en 2019.",
    wiki:'Vierge (constellation)' },
  { id:'vol', fr:'Poisson volant', la:'Volans', star:'β Volantis', season:'Hiver', hemi:'S', area:141, zodiac:false,
    hist:"Les poissons exocets qui fascinaient les équipages de Keyser et de Houtman dans les mers du Sud, immortalisés par Bayer en 1603, volant sous la Carène du grand navire céleste.",
    wiki:'Poisson volant (constellation)' },
  { id:'vul', fr:'Petit Renard', la:'Vulpecula', star:'Anser', season:'Été', hemi:'N', area:268, zodiac:false,
    hist:"« Le petit renard avec l'oie » d'Hevelius (1687) — son étoile principale s'appelle toujours Anser, « l'oie ». Discret mais historique : on y découvrit la nébuleuse de l'Haltère (M27, première nébuleuse planétaire connue, 1764) et le tout premier pulsar (1967).",
    wiki:'Petit Renard' },
]

// Rang par superficie (1 = la plus grande), calculé une fois au chargement
const byArea = [...CONSTELLATIONS_88].sort((a, b) => b.area - a.area)
CONSTELLATIONS_88.forEach(c => { c.rank = byArea.indexOf(c) + 1 })
