// alt/az/mag/rise/set/dist : valeurs de secours, recalculées en direct par
// getSkyPositions() (astro.js). ra en heures, dec en degrés (J2000) pour les
// objets fixes ; les planètes sont calculées via astronomy-engine.
export const SKY_OBJECTS = [
  { id:'jupiter', kind:'Planète', name:'Jupiter', mag:-2.4, alt:52, az:148, r:5.2, color:'#e9c98a', cons:'Taureau',
    info:'Géante gazeuse, la plus brillante ce soir. Les quatre lunes galiléennes sont visibles aux jumelles.', dist:'4,9 UA', rise:'18:42', set:'04:10' },
  { id:'saturn', kind:'Planète', name:'Saturne', mag:0.7, alt:24, az:205, r:4, color:'#e7d6a6', cons:'Verseau',
    info:'Anneaux inclinés à 9°. Un télescope de 60 mm suffit pour les distinguer.', dist:'9,6 UA', rise:'15:30', set:'00:55' },
  { id:'venus', kind:'Planète', name:'Vénus', mag:-4.1, alt:11, az:255, r:4.6, color:'#fdf3d0', cons:'Poissons',
    info:'Étoile du soir éclatante, bas sur l\'horizon ouest après le coucher du Soleil.', dist:'0,72 UA', rise:'09:10', set:'20:48' },
  { id:'mars', kind:'Planète', name:'Mars', mag:0.9, alt:38, az:110, r:3.6, color:'#e0916f', cons:'Cancer',
    info:'Teinte rouge orangée caractéristique. Opposition prochaine en janvier 2027.', dist:'1,4 UA', rise:'21:05', set:'07:30' },
  { id:'vega', kind:'Étoile', name:'Véga', mag:0.0, alt:78, az:300, ra:18.6156, dec:38.78, r:3, color:'#cfe0ff', cons:'Lyre',
    info:'Étoile la plus brillante de la Lyre, sommet du Triangle d\'été. À 25 années-lumière.', dist:'25 al', rise:'—', set:'—' },
  { id:'deneb', kind:'Étoile', name:'Deneb', mag:1.25, alt:71, az:330, ra:20.6905, dec:45.28, r:2.6, color:'#dbe6ff', cons:'Cygne',
    info:'Supergéante bleue, l\'une des étoiles les plus lumineuses connues (≈ 200 000 L☉).', dist:'2 600 al', rise:'—', set:'—' },
  { id:'m31', kind:'Galaxie', name:'M31 — Andromède', mag:3.4, alt:44, az:48, ra:0.7123, dec:41.27, r:2.4, color:'#b9c6e8', cons:'Andromède', deep:true,
    info:'Galaxie spirale, l\'objet le plus lointain visible à l\'œil nu (2,5 M al). Idéale aux jumelles.', dist:'2,5 M al', rise:'—', set:'—' },
  { id:'m13', kind:'Amas', name:'M13 — Hercule', mag:5.8, alt:64, az:285, ra:16.6947, dec:36.46, r:2, color:'#cdbfe8', cons:'Hercule', deep:true,
    info:'Amas globulaire de ~300 000 étoiles. Spectaculaire dans un 200 mm.', dist:'22 000 al', rise:'—', set:'—' },
  { id:'m57', kind:'Nébuleuse', name:'M57 — Anneau', mag:8.8, alt:75, az:305, ra:18.8931, dec:33.03, r:1.7, color:'#9fd6c2', cons:'Lyre', deep:true,
    info:'Nébuleuse planétaire en anneau. Nécessite un télescope ; visible entre Sheliak et Sulafat.', dist:'2 300 al', rise:'—', set:'—' },
  { id:'moon', kind:'Lune', name:'Lune', mag:-12.5, alt:30, az:120, r:5.8, color:'#e8e4da', cons:'—',
    info:'Notre satellite naturel. Le terminateur (limite jour/nuit) offre les reliefs les plus spectaculaires.', dist:'384 400 km', rise:'--:--', set:'--:--' },
  { id:'sirius', kind:'Étoile', name:'Sirius', mag:-1.46, alt:-25, az:340, ra:6.7525, dec:-16.716, r:3.4, color:'#e8f0ff', cons:'Grand Chien',
    info:'L\'étoile la plus brillante du ciel nocturne. Binaire : sa compagne Sirius B est une naine blanche.', dist:'8,6 al', rise:'—', set:'—' },
  { id:'arcturus', kind:'Étoile', name:'Arcturus', mag:-0.05, alt:55, az:215, ra:14.2610, dec:19.18, r:3.1, color:'#f5c889', cons:'Bouvier',
    info:'Géante orange, l\'étoile la plus brillante de l\'hémisphère nord céleste. Prolongez la queue de la Grande Ourse pour la trouver.', dist:'37 al', rise:'—', set:'—' },
  { id:'capella', kind:'Étoile', name:'Capella', mag:0.08, alt:12, az:335, ra:5.2782, dec:45.998, r:3, color:'#f7e3b0', cons:'Cocher',
    info:'Système de quatre étoiles dominé par deux géantes jaunes. Brille bas sur l\'horizon nord en été.', dist:'43 al', rise:'—', set:'—' },
  { id:'altair', kind:'Étoile', name:'Altaïr', mag:0.77, alt:35, az:115, ra:19.8464, dec:8.868, r:2.8, color:'#e6edff', cons:'Aigle',
    info:'Troisième sommet du Triangle d\'été avec Véga et Deneb. Rotation très rapide : 9 h seulement.', dist:'17 al', rise:'—', set:'—' },
  { id:'betelgeuse', kind:'Étoile', name:'Bételgeuse', mag:0.5, alt:-20, az:320, ra:5.9195, dec:7.407, r:2.9, color:'#f0a070', cons:'Orion',
    info:'Supergéante rouge en fin de vie, candidate à une supernova « proche ». Épaule d\'Orion, ciel d\'hiver.', dist:'640 al', rise:'—', set:'—' },
  { id:'antares', kind:'Étoile', name:'Antarès', mag:1.06, alt:15, az:175, ra:16.4901, dec:-26.43, r:2.8, color:'#ef9270', cons:'Scorpion',
    info:'« La rivale de Mars » : supergéante rouge au cœur du Scorpion, basse sur l\'horizon sud en été.', dist:'550 al', rise:'—', set:'—' },
  { id:'aldebaran', kind:'Étoile', name:'Aldébaran', mag:0.86, alt:-10, az:330, ra:4.5987, dec:16.509, r:2.8, color:'#f3b585', cons:'Taureau',
    info:'L\'œil rouge du Taureau, devant l\'amas des Hyades. Étoile du ciel d\'hiver.', dist:'65 al', rise:'—', set:'—' },
  { id:'polaris', kind:'Étoile', name:'Polaire', mag:1.98, alt:49, az:0, ra:2.5303, dec:89.264, r:2.4, color:'#dbe6ff', cons:'Petite Ourse',
    info:'L\'étoile du Nord : son altitude égale votre latitude. Toutes les étoiles semblent tourner autour d\'elle.', dist:'433 al', rise:'—', set:'—' },
  { id:'m42', kind:'Nébuleuse', name:'M42 — Orion', mag:4.0, alt:-25, az:310, ra:5.5881, dec:-5.39, r:2.2, color:'#e8a8c0', cons:'Orion', deep:true,
    info:'La grande nébuleuse d\'Orion, pouponnière d\'étoiles visible à l\'œil nu sous l\'épée d\'Orion. Ciel d\'hiver.', dist:'1 350 al', rise:'—', set:'—' },
  { id:'m45', kind:'Amas', name:'M45 — Pléiades', mag:1.6, alt:-8, az:20, ra:3.7833, dec:24.117, r:2.6, color:'#b9d4f5', cons:'Taureau', deep:true,
    info:'Les Sept Sœurs : amas ouvert spectaculaire aux jumelles, enveloppé de nébulosités bleutées.', dist:'444 al', rise:'—', set:'—' },
  { id:'ngc869', kind:'Amas', name:'NGC 869/884 — Double amas', mag:4.3, alt:20, az:25, ra:2.3333, dec:57.13, r:2, color:'#cdd8f0', cons:'Persée', deep:true,
    info:'Deux amas ouverts côte à côte entre Persée et Cassiopée. Superbe aux jumelles, circumpolaire.', dist:'7 500 al', rise:'—', set:'—' },
  { id:'m44', kind:'Amas', name:'M44 — Crèche', mag:3.7, alt:5, az:290, ra:8.6733, dec:19.67, r:2, color:'#d8e2f5', cons:'Cancer', deep:true,
    info:'Amas de la Ruche : nuage d\'étoiles visible à l\'œil nu sous un bon ciel, résolu aux jumelles.', dist:'577 al', rise:'—', set:'—' },
]

// stars : [ra (heures), dec (degrés)] J2000 — positions projetées en direct
export const CONSTELLATIONS = [
  { name:'Cygne', // Croix du Nord : Deneb, Sadr, Albireo + bras Delta/Epsilon
    stars:[[20.6905,45.28],[20.3705,40.26],[19.5121,27.96],[19.7496,45.13],[20.7702,33.97]],
    lines:[[0,1],[1,2],[3,1],[1,4]] },
  { name:'Lyre', // Véga, Sheliak, Sulafat
    stars:[[18.6156,38.78],[18.8347,33.36],[18.9824,32.69]],
    lines:[[0,1],[1,2],[2,0]] },
  { name:'Grande Ourse', // Grand Chariot : Dubhe, Merak, Phecda, Megrez, Alioth, Mizar, Alkaid
    stars:[[11.0621,61.75],[11.0307,56.38],[11.8972,53.69],[12.2571,57.03],[12.9005,55.96],[13.3988,54.93],[13.7923,49.31]],
    lines:[[0,1],[1,2],[2,3],[3,0],[3,4],[4,5],[5,6]] },
  { name:'Cassiopée', // le W : Caph, Schedar, Gamma Cas, Ruchbah, Segin
    stars:[[0.1530,59.15],[0.6751,56.54],[0.9451,60.72],[1.4303,60.24],[1.9066,63.67]],
    lines:[[0,1],[1,2],[2,3],[3,4]] },
]

export const PLANETS = [
  { id:'mercure', name:'Mercure', sub:'Planète tellurique', color:'#b8a48a', glow:'#cdb79c',
    img:'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Mercury_in_true_color.jpg/480px-Mercury_in_true_color.jpg',
    nameEn:'mercury planet messenger',
    diam:'4 879 km', mass:'0,055 M⊕', day:'176 j', year:'88 j', moons:0, temp:'−173 → 427 °C', dist:'0,39 UA',
    note:'La plus petite planète et la plus proche du Soleil. Sans atmosphère notable, criblée de cratères.' },
  { id:'venus', name:'Vénus', sub:'Planète tellurique', color:'#d9b779', glow:'#e7cd96',
    img:'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Venus-real_color.jpg/480px-Venus-real_color.jpg',
    nameEn:'venus planet atmosphere clouds',
    diam:'12 104 km', mass:'0,815 M⊕', day:'243 j', year:'225 j', moons:0, temp:'464 °C', dist:'0,72 UA',
    note:'Effet de serre extrême sous une atmosphère de CO₂. Rotation rétrograde, la plus lente du système.' },
  { id:'terre', name:'Terre', sub:'Planète tellurique', color:'#6f9fd0', glow:'#8fc0e8',
    img:'https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/The_Earth_seen_from_Apollo_17.jpg/480px-The_Earth_seen_from_Apollo_17.jpg',
    nameEn:'earth from orbit space',
    diam:'12 742 km', mass:'1 M⊕', day:'24 h', year:'365,25 j', moons:1, temp:'15 °C moy.', dist:'1 UA',
    note:'La seule planète connue abritant la vie. Hydrosphère liquide et champ magnétique protecteur.' },
  { id:'mars', name:'Mars', sub:'Planète tellurique', color:'#c5704a', glow:'#dd8a63',
    img:'https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/OSIRIS_Mars_true_color.jpg/480px-OSIRIS_Mars_true_color.jpg',
    nameEn:'mars planet surface red planet',
    diam:'6 779 km', mass:'0,107 M⊕', day:'24,6 h', year:'687 j', moons:2, temp:'−63 °C moy.', dist:'1,52 UA',
    note:'La planète rouge. Olympus Mons culmine à 22 km. Indices d\'eau liquide passée.' },
  { id:'jupiter', name:'Jupiter', sub:'Géante gazeuse', color:'#cda972', glow:'#e3c391',
    img:'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Jupiter_and_its_shrunken_Great_Red_Spot.jpg/480px-Jupiter_and_its_shrunken_Great_Red_Spot.jpg',
    nameEn:'jupiter great red spot',
    diam:'139 820 km', mass:'318 M⊕', day:'9,9 h', year:'11,9 ans', moons:95, temp:'−108 °C', dist:'5,2 UA',
    note:'La plus massive. La Grande Tache rouge est un anticyclone plus large que la Terre.' },
  { id:'saturne', name:'Saturne', sub:'Géante gazeuse', color:'#d8c188', glow:'#ecd9a4',
    img:'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Saturn_during_Equinox.jpg/480px-Saturn_during_Equinox.jpg',
    nameEn:'saturn planet rings cassini',
    diam:'116 460 km', mass:'95 M⊕', day:'10,7 h', year:'29,5 ans', moons:146, temp:'−139 °C', dist:'9,5 UA',
    note:'Système d\'anneaux de glace iconique. Densité inférieure à celle de l\'eau.' },
  { id:'uranus', name:'Uranus', sub:'Géante de glace', color:'#9fd3d8', glow:'#bce6ea',
    img:'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Uranus2.jpg/480px-Uranus2.jpg',
    nameEn:'uranus planet voyager',
    diam:'50 724 km', mass:'14,5 M⊕', day:'17,2 h', year:'84 ans', moons:28, temp:'−197 °C', dist:'19,2 UA',
    note:'Inclinée à 98° : elle roule sur son orbite. Atmosphère de méthane bleu-vert.' },
  { id:'neptune', name:'Neptune', sub:'Géante de glace', color:'#5a7fd6', glow:'#7f9fe8',
    img:'https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Neptune_Full.jpg/480px-Neptune_Full.jpg',
    nameEn:'neptune planet voyager',
    diam:'49 244 km', mass:'17 M⊕', day:'16,1 h', year:'165 ans', moons:16, temp:'−201 °C', dist:'30,1 UA',
    note:'Vents les plus violents du système solaire (2 100 km/h). Découverte par le calcul en 1846.' },
]

export const JWST = [
  { id:'jw1', slot:'jw-carina', name:'Falaises cosmiques', target:'NGC 3324 · Carène', instr:'NIRCam', date:'Juil. 2022',
    note:'Bordure de la nébuleuse de la Carène. Les pics atteignent 7 années-lumière de haut.' },
  { id:'jw2', slot:'jw-srings', name:'Anneaux de Saturne', target:'Saturne', instr:'NIRCam', date:'Juin 2023',
    note:'Anneaux d\'une netteté inédite en proche infrarouge ; le disque apparaît sombre (méthane).' },
  { id:'jw3', slot:'jw-pillars', name:'Piliers de la Création', target:'M16 · Aigle', instr:'NIRCam + MIRI', date:'Oct. 2022',
    note:'Colonnes de gaz et poussière où naissent de nouvelles étoiles, revisitées par Webb.' },
  { id:'jw4', slot:'jw-deep', name:'Premier champ profond', target:'SMACS 0723', instr:'NIRCam', date:'Juil. 2022',
    note:'Amas de galaxies agissant comme lentille gravitationnelle ; certaines galaxies à 13 Mds d\'al.' },
  { id:'jw5', slot:'jw-phantom', name:'Galaxie fantôme', target:'M74', instr:'MIRI', date:'Août 2022',
    note:'Spirale parfaite vue de face ; le moyen infrarouge révèle les filaments de poussière.' },
  { id:'jw6', slot:'jw-neptune', name:'Neptune et ses anneaux', target:'Neptune', instr:'NIRCam', date:'Sept. 2022',
    note:'Première image nette des anneaux de Neptune depuis Voyager 2 (1989).' },
]

export const ANOMALIES = [
  { id:'dm', name:'Matière noire', tag:'~27 % de l\'univers', color:'#7ea6e6',
    wikiUrl:'https://fr.wikipedia.org/wiki/Matière_noire',
    short:'Masse invisible qui ne rayonne pas mais courbe la lumière et structure les galaxies.',
    body:'Postulée pour expliquer la rotation des galaxies, trop rapide pour la seule matière visible. Candidats : WIMPs, axions, neutrinos stériles. Aucune détection directe à ce jour ; les contraintes se resserrent (LZ, XENONnT).',
    facts:[['Fraction d\'énergie','26,8 %'],['Preuve clé','Courbes de rotation'],['Détection','Indirecte / gravitationnelle']] },
  { id:'de', name:'Énergie noire', tag:'~68 % de l\'univers', color:'#b08ae0',
    wikiUrl:'https://fr.wikipedia.org/wiki/Énergie_noire',
    short:'Composante qui accélère l\'expansion de l\'univers depuis ~5 milliards d\'années.',
    body:'Mise en évidence en 1998 via les supernovæ de type Ia. Décrite par la constante cosmologique Λ (w ≈ −1). Les relevés DESI (2024-25) suggèrent une possible évolution de w, ce qui défierait le modèle standard.',
    facts:[['Fraction d\'énergie','68,3 %'],['Paramètre','w ≈ −1'],['Découverte','SN Ia, 1998 (Nobel 2011)']] },
  { id:'cr', name:'Rayons cosmiques', tag:'Particules ultra-énergétiques', color:'#84d3a9',
    wikiUrl:'https://fr.wikipedia.org/wiki/Rayon_cosmique',
    short:'Noyaux et particules accélérés à des énergies inaccessibles aux accélérateurs terrestres.',
    body:'Principalement des protons. Les événements les plus extrêmes (« Oh-My-God », 3×10²⁰ eV) dépassent la limite GZK. Origines probables : supernovæ, AGN, sursauts gamma. Observés par Pierre Auger et Telescope Array.',
    facts:[['Énergie record','3,2 × 10²⁰ eV'],['Composition','~90 % protons'],['Observatoire','Pierre Auger']] },
  { id:'h0', name:'Tension de Hubble', tag:'Crise cosmologique', color:'#e7bd6e',
    wikiUrl:'https://fr.wikipedia.org/wiki/Tension_de_Hubble',
    short:'Désaccord persistant entre deux mesures du taux d\'expansion de l\'univers.',
    body:'L\'univers primordial (CMB, Planck) donne H₀ ≈ 67,4 km/s/Mpc ; l\'univers local (céphéides + SN Ia, SH0ES) donne ≈ 73. L\'écart dépasse 5σ — soit une erreur systématique, soit une physique nouvelle.',
    facts:[['Planck (CMB)','67,4 km/s/Mpc'],['SH0ES (local)','73,0 km/s/Mpc'],['Tension','> 5 σ']] },
  { id:'bh', name:'Trous noirs', tag:'Singularités gravitationnelles', color:'#9aa6c4',
    wikiUrl:'https://fr.wikipedia.org/wiki/Trou_noir',
    short:'Régions où la gravité empêche toute fuite, y compris de la lumière.',
    body:'Du stellaire (quelques M☉) au supermassif (millions à milliards de M☉). Premières images par l\'EHT : M87* (2019) et Sgr A* (2022). Les ondes gravitationnelles (LIGO/Virgo) sondent leurs fusions.',
    facts:[['Sgr A* (Voie lactée)','4,3 M☉ millions'],['1ʳᵉ image','M87*, 2019'],['Ondes grav.','LIGO/Virgo, 2015']] },
]

export const THEORIES = [
  { id:'bb', name:'Big Bang', when:'Modèle standard', icon:'•',
    wikiUrl:'https://fr.wikipedia.org/wiki/Big_Bang',
    short:'L\'univers en expansion à partir d\'un état chaud et dense il y a 13,8 Mds d\'années.',
    body:'Soutenu par trois piliers : l\'expansion (loi de Hubble-Lemaître), le fond diffus cosmologique à 2,7 K, et l\'abondance des éléments légers (nucléosynthèse primordiale).' },
  { id:'infl', name:'Inflation cosmique', when:'10⁻³⁶ s après t=0', icon:'↑',
    wikiUrl:'https://fr.wikipedia.org/wiki/Inflation_cosmologique',
    short:'Expansion exponentielle fulgurante de l\'univers très primordial.',
    body:'Proposée par Guth (1980), elle résout les problèmes de l\'horizon et de la platitude, et explique l\'origine quantique des fluctuations à grande échelle observées dans le CMB.' },
  { id:'lcdm', name:'Modèle ΛCDM', when:'Cadre de concordance', icon:'Λ',
    wikiUrl:'https://fr.wikipedia.org/wiki/Modèle_de_concordance',
    short:'Univers plat composé d\'énergie noire (Λ) et de matière noire froide.',
    body:'Le modèle standard de la cosmologie : 68 % d\'énergie noire, 27 % de matière noire, 5 % de matière ordinaire. Ajuste remarquablement le CMB et les grandes structures.' },
  { id:'mw', name:'Multivers', when:'Hypothèse spéculative', icon:'∞',
    wikiUrl:'https://fr.wikipedia.org/wiki/Multivers',
    short:'Notre univers serait l\'un parmi une multitude d\'autres.',
    body:'Issu de l\'inflation éternelle ou de l\'interprétation des mondes multiples. Débattu : difficilement falsifiable, il reste à la frontière de la physique et de la philosophie.' },
  { id:'string', name:'Théorie des cordes', when:'Gravité quantique', icon:'≈',
    wikiUrl:'https://fr.wikipedia.org/wiki/Théorie_des_cordes',
    short:'Les particules seraient des cordes vibrantes dans un espace à 10/11 dimensions.',
    body:'Candidate à l\'unification de la mécanique quantique et de la relativité générale. Élégante mathématiquement mais sans prédiction expérimentale confirmée à ce jour.' },
]

export const NEWS = [
  { id:'n1', cat:'Lancement', org:'SpaceX', title:'Starship — vol d\'essai orbital V3', when:'12 juin 2026', tag:'à venir',
    detail:'Premier vol de la version 3 depuis Starbase, avec tentative de récupération du Super Heavy.' },
  { id:'n2', cat:'Mission', org:'ESA', title:'JUICE — survol de Vénus', when:'31 août 2026', tag:'trajet',
    detail:'Assistance gravitationnelle vers Jupiter ; arrivée dans le système jovien prévue en 2031.' },
  { id:'n3', cat:'Programme', org:'NASA', title:'Artemis II — équipage autour de la Lune', when:'Fév. 2026', tag:'proche',
    detail:'Premier vol habité du programme : survol lunaire sans alunissage, 10 jours de mission.' },
  { id:'n4', cat:'Science', org:'ESA', title:'Euclid — 1ʳᵉ livraison de données', when:'Mars 2026', tag:'publié',
    detail:'Cartographie de millions de galaxies pour sonder énergie noire et matière noire.' },
]

export const CONFERENCES = [
  { id:'c1', name:'European Astronomical Society — EAS 2026', place:'Cracovie, Pologne', date:'22–26 juin 2026', topic:'Réunion annuelle européenne', url:'https://eas.unige.ch/EAS2026/' },
  { id:'c2', name:'COSPAR Scientific Assembly', place:'Florence, Italie', date:'18–26 juil. 2026', topic:'Recherche spatiale', url:'https://cosparhq.cnes.fr/' },
  { id:'c3', name:'IAU — General Assembly', place:'Le Cap, Afrique du Sud', date:'3–14 août 2027', topic:'Union astronomique internationale', url:'https://www.iau.org/' },
  { id:'c4', name:'Rencontres du Ciel et de l\'Espace', place:'Cité des sciences, Paris', date:'7–8 nov. 2026', topic:'Grand public & amateurs', url:'https://www.cite-sciences.fr/' },
]

export const PEOPLE = [
  { id:'p1', name:'Adam Riess', role:'Prix Nobel 2011', field:'Tension de Hubble',
    wikiUrl:'https://fr.wikipedia.org/wiki/Adam_Riess',
    note:'Codécouvreur de l\'accélération de l\'expansion. Mène l\'équipe SH0ES, au cœur du débat sur H₀.' },
  { id:'p2', name:'Brian Schmidt', role:'Prix Nobel 2011', field:'Énergie noire',
    wikiUrl:'https://fr.wikipedia.org/wiki/Brian_Schmidt',
    note:'Codirigea le High-z Supernova Search qui révéla l\'expansion accélérée de l\'univers.' },
  { id:'p3', name:'Andrea Ghez', role:'Prix Nobel 2020', field:'Trou noir galactique',
    wikiUrl:'https://fr.wikipedia.org/wiki/Andrea_Ghez',
    note:'A démontré la présence de Sgr A* au centre de la Voie lactée par le suivi des étoiles.' },
  { id:'p4', name:'Jocelyn Bell Burnell', role:'Découverte des pulsars', field:'Astrophysique',
    wikiUrl:'https://fr.wikipedia.org/wiki/Jocelyn_Bell_Burnell',
    note:'Détecta le premier pulsar en 1967, ouvrant l\'étude des étoiles à neutrons.' },
  { id:'p5', name:'Françoise Combes', role:'Collège de France', field:'Dynamique des galaxies',
    wikiUrl:'https://fr.wikipedia.org/wiki/Françoise_Combes',
    note:'Spécialiste de la matière noire et de la formation des galaxies ; médaille d\'or du CNRS.' },
]

export const BOOKS = [
  { id:'b1', title:'L\'Univers à portée de main', author:'Christophe Galfard', year:'2015', note:'Vulgarisation narrative du cosmos, de l\'atome aux confins.' },
  { id:'b2', title:'Astrophysique pour les pressés', author:'Neil deGrasse Tyson', year:'2017', note:'L\'essentiel de la cosmologie moderne en chapitres courts.' },
  { id:'b3', title:'Trous noirs et distorsions du temps', author:'Kip Thorne', year:'1994', note:'Référence sur la relativité générale par un prix Nobel.' },
  { id:'b4', title:'La Plus Belle Histoire du monde', author:'Reeves, de Rosnay…', year:'1996', note:'Du Big Bang à l\'humain, raconté à plusieurs voix.' },
  { id:'b5', title:'Dernières nouvelles des trous noirs', author:'Aurélien Barrau', year:'2021', note:'État de l\'art accessible sur la gravité extrême.' },
]

export const PHOTO_SITES = [
  { id:'s1', name:'NASA — APOD', url:'apod.nasa.gov', note:'L\'image astronomique du jour, depuis 1995.' },
  { id:'s2', name:'ESA/Hubble', url:'esahubble.org', note:'Archives haute résolution de Hubble.' },
  { id:'s3', name:'Webb Space Telescope', url:'webbtelescope.org', note:'Galerie officielle des images du JWST.' },
  { id:'s4', name:'Astrobin', url:'astrobin.com', note:'Plateforme de référence des astrophotographes amateurs.' },
  { id:'s5', name:'ESO', url:'eso.org/public/images', note:'Observatoires européens au Chili (VLT, ALMA).' },
]
